repo_url: https://github.com/Requisitos-de-Software/2023.1-BilheteriaDigital
repo_name: 2023.1-BilheteriaDigital

markdown_extensions:
  - attr_list
site_name: Bilheteria Digital
nav:
  - Home: index.md
  - Planejamento:
      - Aplicativo escolhido: aplicativo.md
      - Ferramentas: ferramentas.md
      - Cronograma: cronograma.md
  - Pré-Rastreabilidade:
      - Rich Picture: rich_picture.md 
  - Atas:
      - Ata 1: atas/Requisitos_Ata_01.md
      - Ata 2: atas/Requisitos_Ata_02.md
      - Ata 3: atas/Requisitos_Ata_03.md
  

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Claro
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-night
        name: Escuro
  
  language: pt-BR
  favicon: assets/bilheteria.png
  logo: assets/bilheteria.png

extra:
  version:
    provider: mike

