repo_url: https://github.com/Requisitos-de-Software/2023.1-BilheteriaDigital
repo_name: 2023.1-BilheteriaDigital

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

site_name: Bilheteria Digital
nav:
  - Home: index.md
  - Apresentação:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Apresentação 3: apresentacoes/apresentacao3.md
      - Apresentação 4: apresentacoes/apresentacao4.md
  - Atas:
      - Ata 1: atas/Requisitos_Ata_01.md
      - Ata 2: atas/Requisitos_Ata_02.md
      - Ata 3: atas/Requisitos_Ata_03.md
      - Ata 4: atas/Requisitos_Ata_04.md
      - Ata 5: atas/Requisitos_Ata_05.md
      - Ata 6: atas/Requisitos_Ata_06.md
      - Ata 7: atas/Requisitos_Ata_07.md
      - Ata 8: atas/Requisitos_Ata_08.md
      - Ata 9: atas/Requisitos_Ata_09.md
  - Pré-Rastreabilidade:
      - Rich Picture: rastreabilidade/rich_picture.md
  - Planejamento:
      - Aplicativo escolhido: planejamento/aplicativo.md
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md
      - Metodologia: planejamento/metodologia.md
  - Elicitação:
      - Perfil de Usuário: elicitacao/perfil_de_usuario.md
      - Personas: elicitacao/personas.md
      - Técnicas:
          - Introspecção: elicitacao/tecnicas/introspeccao.md
          - Questionário: elicitacao/tecnicas/questionario.md
          - Brainstorming: elicitacao/tecnicas/brainstorming.md
          - Observação: elicitacao/tecnicas/observacao.md
      - Priorização:
          - $100: elicitacao/priorizacao/100.md
          - First Things First: elicitacao/priorizacao/firstThingsfirst.md
          - Three Level Scale: elicitacao/priorizacao/threeLvlScale.md
      - Requisitos Elicitados: elicitacao/requisitos_elicitados.md
  - Modelagem:
      - Casos de uso: modelagem/useCase.md
      - Especificação Suplementar: modelagem/especificacao-suplementar.md
      - Cenários: modelagem/cenarios.md
      - Léxicos: modelagem/lexicos.md
      - Ágil:
          - NFR Framework: modelagem/agil/nfrframework.md
          - Backlog: modelagem/agil/backlog.md
          - Histórias de Usuário: modelagem/agil/historia-de-usuario.md
  - Verificação:
      - Grupo + 1:
          - Entrega 1:
              - Planejamento da Verificação da Entrega 1 do Grupo 2: verificacao/grupo2/entrega1/planejamento-verificacao-e1-grupo2.md
          - Entrega 2:
              - Planejamento da Verificação da Entrega 2 do Grupo 2: verificacao/grupo2/entrega2/planejamento-verificacao-e2-grupo2.md
          - Entrega 3:
              - Planejamento da Verificação da Entrega 3 do Grupo 2: verificacao/grupo2/entrega3/planejamento-verificacao-e3-grupo2.md
              - Verificação da Especificação Suplementar: verificacao/grupo2/entrega3/especificacao-suplementar.md
              - Verificação dos Cenários: verificacao/grupo2/entrega3/cenarios.md
          - Entrega 4:
              - Planejamento da Verificação da Entrega 4 do Grupo 2: verificacao/grupo2/entrega4/planejamento-verificacao-e4-grupo2.md
          - Entrega 5:
              - Planejamento da Verificação da Entrega 5 do Grupo 2: verificacao/grupo2/entrega5/planejamento-verificacao-e5-grupo2.md
      - Grupo:
          - Entrega 1:
              - Planejamento da Verificação da Entrega 1: verificacao/grupo/entrega1/planejamento-verificacao-e1-grupo.md
          - Entrega 2:
              - Planejamento da Verificação da Entrega 2: verificacao/grupo/entrega2/planejamento-verificacao-e2-grupo.md
          - Entrega 3:
              - Planejamento da Verificação da Entrega 3: verificacao/grupo/entrega3/planejamento-verificacao-e3-grupo.md
          - Entrega 4:
              - Planejamento da Verificação da Entrega 4: verificacao/grupo/entrega4/planejamento-verificacao-e4-grupo.md
          - Entrega 5:
              - Planejamento da Verificação da Entrega 5: verificacao/grupo/entrega5/planejamento-verificacao-e5-grupo.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Escuro

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Claro

  language: pt-BR
  favicon: assets/bilheteria.png
  logo: assets/bilheteria.png

extra:
  version:
    provider: mike

extra_css: [stylesheets/extra.css]
