repo_url: https://github.com/Requisitos-de-Software/2023.1-BilheteriaDigital
repo_name: 2023.1-BilheteriaDigital

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
site_name: Bilheteria Digital
nav:
  - Home: index.md
  - Apresentação: apresentacao.md
  - Pré-Rastreabilidade:
      - Rich Picture: rastreabilidade/rich_picture.md
  - Planejamento:
      - Aplicativo escolhido: planejamento/aplicativo.md
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md
      - Metodologia: planejamento/metodologia.md
  - Elicitação:
      - Introspecção: elicitacao/introspeccao.md
      - Brainstorming: elicitacao/brainstorming.md
  - Atas:
      - Ata 1: atas/Requisitos_Ata_01.md
      - Ata 2: atas/Requisitos_Ata_02.md
      - Ata 3: atas/Requisitos_Ata_03.md
      - Ata 4: atas/Requisitos_Ata_04.md
      - Ata 5: atas/Requisitos_Ata_05.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Escuro

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Claro


  language: pt-BR
  favicon: assets/bilheteria.png
  logo: assets/bilheteria.png

  


extra:
  version:
    provider: mike

extra_css: [stylesheets/extra.css]
